### ISSUE TITLE
JOSS review: documentation

### ISSUE THREAD

**Issue by yhtang** [elizabethnewman/hessQuik#2]
Hi, I'll use this as a master thread for issues related to the **documentation** section of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4171) of your submission "hessQuik: Fast Hessian computation of composite functions".

Below are the specific check items that are not present in the current README file of this repo:

- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x]  Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x]  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by elizabethnewman** [comment]
Dear @yhtang

Thank you for making this master thread for documentation issues.  I have some questions regarding the four items above:

1. Is the statement of need required in the README file?  My impression was this was required for the documentation in the paper, but not in the README.  I have not seen a Statement of Need in the README file in all published JOSS papers, but perhaps I misunderstood.

2. What is missing in the README file about the functionality documentation?  I had thought the Getting Started section served this purpose, but is there something else you wanted to see?

3. We included automated tests in the tests directory https://github.com/elizabethnewman/hessQuik/tree/main/hessQuik/tests.  This is linked in relevant places in the repository.  Is this sufficient? 

4. There is a Contributing section and Reporting Bugs section of the README file.  Is there something else I need to include or something unclear?

Thank you for reviewing this paper and repository!

**Comment by yhtang** [comment]
Hi Elizabeth,

> 1. Is the statement of need required in the README file?  My impression was this was required for the documentation in the paper, but not in the README.  I have not seen a Statement of Need in the README file in all published JOSS papers, but perhaps I misunderstood.

According to the reviewer's checklist that I was given, the statement of need is required for both the *documentation* and the *paper*. Usually, the documentation of the software is hosted as a standalone site/page on places such as Github Pages or ReadTheDocs. In this case, it seems to me that the README file serves the role of the documentation for the hessQuik and hence why my initial comments targeted the README file. Definitely let me know if a documentation site is actually hosted somewhere that I neglected.

> 2. What is missing in the README file about the functionality documentation?  I had thought the Getting Started section served this purpose, but is there something else you wanted to see?

I think a common practice is to document functionality using a two-component strategy that consists of presenting a 'user guide' and an 'API documentation'. The user guide is a manual-style document that explains in natural language how the package is structured and how typical usage should occur. The API documentation is usually automatically generated using tools such as Sphinx or MkDocs to enumerate all publicly accessible methods, classes, and modules etc. Our software [FunFact](https://funfact.readthedocs.io/en/latest/) might serve as a (hopefully not too terrible) example of this pattern.

> 3. We included automated tests in the tests directory https://github.com/elizabethnewman/hessQuik/tree/main/hessQuik/tests.  This is linked in relevant places in the repository.  Is this sufficient?

I did find the tests. Maybe this is my misunderstanding, but I was additionally looking for a mechanism that automatically executes the tests every time when new changes are introduced to the code. This is usually implemented using continuous integration services such as Github Actions or Travis CI or similar things. I suggest we fall back to the main review thread and consult the editor on this matter.

> 4. There is a Contributing section and Reporting Bugs section of the README file.  Is there something else I need to include or something unclear?

This is probably my bad that I missed this section initially. Let's check this box now :grin:

**Comment by GregaVrbancic** [comment]
Hi Elizabeth,

I am the other reviewer of your submission. Overall, I agree with @yhtang comments regarding the documentation. In current state could be a bit confusing since and hard to find, since there are bits of documentation all over the project structure. I would appreciate at least some navigation in the main README file, so that one can navigate to the specific part of documentation more easily.

Regarding the tests, I have no problem with manual tests as long there is a brief description on how to run them. That is also in line with [JOSS review criteria.](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

**Comment by GregaVrbancic** [comment]
Looking more in depth I see the major problem, regarding the documentation, that API method documentation is missing. In my opinion, this concern should be addressed first.

**Comment by elizabethnewman** [comment]
Dear @yhtang and @GregaVrbancic,

Thank you for your feedback about the repository and for answering my questions - it is very helpful.  I will work on clarifying the API method documentation and see if I can add automatic tests.  The latter does not seem as straightforward due to the nature of this repository (tests often need to be tailored to the specific layer or network), but I will certainly do my best!

**Comment by elizabethnewman** [comment]
Dear @yhtang and @GregaVrbancic 

Thank you for your suggestions and for reviewing this repository.  As requested, I have added new API functionality documentation, linked in the README, and have added a continuous integration workflow using Github Actions.  I believe these changes make the repository much more user-friendly and fulfill the JOSS requirements (I hope!).  Please let me know if there is more I can do to improve the documentation.

**Comment by yhtang** [comment]
Thanks for the update! Given that the overall structure of the documentation is largely in place now, I'm going to close this issue. We can then fall back to the main review thread and address any remaining issues there.
