### ISSUE TITLE
[JOSS review] Packaging

### ISSUE THREAD

**Issue by GregaVrbancic** [elizabethnewman/hessQuik#4]
Hi @elizabethnewman,

firstly, I would like to thank you for a great job with documentation. Here is just a small suggestion regarding the packaging of the library. I would suggest you upload the package to pypi. This would enable users to find and install the library more easily. Again, this is in my opinion not mandatory, but it would be nice to have 🙂

**Comment by elizabethnewman** [comment]
Hi @GregaVrbancic 

Thank you for your suggestion about uploading the package to PyPI.  I have done so and added instructions to the Github README and to the documentation about importing from PyPI.  I hope this makes installation easier!

**Comment by GregaVrbancic** [comment]
@elizabethnewman thank you once again 🙂
